# Site settings 配置站点
title: '熊二狗的独立博客'
description: '熊二狗的独立博客'
keyword: '熊二狗的独立博客'
url: 'http://nettyxiong.github.io' # your host

# if you don't need baseurl, you should leave this value blank.
# baseurl: 'http://netttxiong.github.io/'

# local test
baseurl: ''

# Navigation links
nav:
  home: '/'
  tags: '/tags.html'

# Footer
footer:
  since: 2015

# Author 配置博主信息
author: '熊思'
nickname: '熊二狗'
bio: '热爱技术&设计，简单乐观爱创造'
avatar: '/assets/img/profile.png'

# Search
search: true

# Night mode
nightMode: true

# Comments 评论功能
comments:
  gitalk: true 
  gitalk_clientID: '0710e2d1a05a4e6851c9'
  gitalk_Secret: 'f3bf238ac00991d863d83ed92d4fa290dcdd178e'
  gitalk_repo: 'nettyxiong.github.io'
  gitalk_owner: 'nettyxiong'
  gitalk_admin: 'nettyxiong'
  distractionFreeMode: true

# MathJax 公式支持 by Ray-Eldath
mathjax: true

# Share
social-share: true
social-share-items: ['wechat', 'weibo', 'douban']

# theme color 主题皮肤
theme-color: 'default'  # pink or default

# Post header background patterns (when the post no cover): circuitBoard, overlappingCircles, food, glamorous, ticTacToe, seaOfClouds
postPatterns: 'seaOfClouds'

# SNS settings 配置社交网站
# url: email, weibo, zhihu, twitter, instagram, juejin, github, douban, facebook, dribble, uicn, jianshu, medium, linkedin
sns:
  weibo: '//weibo.com/sxiong5'
  zhihu: '//zhihu.com/people/xiong-si-50/'
  github: '//github.com/nettyxiong'
  email: 'nettyxiong@tencent.com'

# Tags 设置标签
recommend-tags: true # whether or not display recommend-tags on the sidebar
recommend-condition-size: 12 # a tag will be recommended if the size of it is more than this value

# Build settings
paginate: 6
paginate_path: 'page:num'
exclude: ['node_modules', 'dev', 'package.json', 'gulpfile.js', '.gitignore', 'README.md']

# Markdown
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  syntax_highlighter: rouge

# RSS
RSS: false

# Permalink
# See: https://github.com/kaeyleo/jekyll-theme-H2O/issues/35
permalink: /:year/:month/:day/:title.html

# Plugins
plugins: [jekyll-paginate]
